--Rename this file to V9001_1__Delete_data_HANA.sql.hana if the database used is not SAP HANA

DELETE FROM BILL_ORDERPOSITION;
DELETE FROM RESTAURANTTABLE;
DELETE FROM PRODUCT;
DELETE FROM OFFER;
DELETE FROM ORDERPOSITION;
DELETE FROM BILL;
DELETE FROM RESTAURANTORDER;

--Keep Staffmembers to allow authentication
--DELETE FROM STAFFMEMBER;
