version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/angular"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/node"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
