version: '2'

services:
  mtsangular:
    build: 'angular/'
    restart: always
    container_name: 'mts_angular'
    networks:
      - my-thai-star
    ports:
      - '8080:80'
      - '443:443'
  mtsjava:
    build: 'java/'
    restart: always
    container_name: 'mts_java'
    ports:
      - 9090:8080
    networks:
      - my-thai-star

networks:
  my-thai-star:
    driver: bridge