node {
    stage('Check out MyThaiStar') {
        deleteDir()
        git branch: 'develop', credentialsId: 'github-devonfw-ci', url: 'https://github.com/oasp/my-thai-star'
    }
   
    stage('Load tools') {
        def node = tool name: 'Node 8.9 LTS', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
        env.PATH = "${node}/bin:${env.PATH}"
        tool 'Chrome-stable'
        tool name: 'Maven 3.3.9', type: 'maven'
        env.JAVA_HOME="${tool 'OpenJDK 1.8'}"
        env.PATH="${env.JAVA_HOME}/bin:${env.PATH}"
    }
    
    stage('CLIENT Install dependencies') {
        sh """
            cd angular
            npm install
        """
    }
    
    stage('SERVER Install dependencies') {
        withMaven(globalMavenSettingsConfig: '9d437f6e-46e7-4a11-a8d1-2f0055f14033', jdk: 'OpenJDK 1.8', maven: 'Maven 3.3.9') {
            sh "cd java/mtsj && mvn clean install -Dmaven.test.skip=true"
        }
    }
    
    stage('CLIENT Code Quality') {
        sh """
            cd angular
            npm run lint
        """
    }
    
    stage('SERVER Code Quality') {
        def scannerHome = tool 'SonarQube Scanner';
        withSonarQubeEnv('SonarQube') 
        {
            sh "cd java/mtsj && ${scannerHome}/bin/sonar-scanner -Dsonar.login=admin -Dsonar.password=admin -Dsonar.projectKey=testmythaistar -Dsonar.projectName=test_my_thai_star -Dsonar.projectVersion=1.0 -Dsonar.sources=. -Dsonar.language=java"
        }
    }
    
    stage('CLIENT Unit Tests') {
        sh """
            cd angular
            ng test --browsers PhantomJS --single-run
        """
    }
    
    stage('SERVER Unit Tests') {
        configFileProvider([configFile(fileId: '9d437f6e-46e7-4a11-a8d1-2f0055f14033', variable: 'MAVEN_SETTINGS')]) {
            sh "cd java/mtsj && mvn -s $MAVEN_SETTINGS test"
        }
    }

    stage('Build Artifacts') {
        parallel (
            "CLIENT" : {
                sh """
                    cd angular
                    ng build --env=prodcompose --build-optimizer
                """
            },
            "SERVER" : {
                configFileProvider([configFile(fileId: '9d437f6e-46e7-4a11-a8d1-2f0055f14033', variable: 'MAVEN_SETTINGS')]) {
                    sh "cd java/mtsj && mvn -s $MAVEN_SETTINGS clean deploy -Dmaven.test.skip=true"
                }
            }
        )
    }
    
    stage('Deploy Artifacts') {
        sshagent (credentials: ['3d0fa2a4-5cf0-4cf5-a3fd-23655eb33c11']) {
            sh """
                # Copy client artifact and Dockerfile to DP angular directory
                scp -o StrictHostKeyChecking=no -r angular/Dockerfile root@${SERVER_IP}:/root/mythaistar/angular
                scp -o StrictHostKeyChecking=no -r angular/dist root@${SERVER_IP}:/root/mythaistar/angular
                
                # Copy server artifact and Dockerfile to DP java directory
                scp -o StrictHostKeyChecking=no -r java/Dockerfile root@${SERVER_IP}:/root/mythaistar/java
                scp -o StrictHostKeyChecking=no -r java/mtsj/server/target/mythaistar.war root@${SERVER_IP}:/root/mythaistar/java
                
                # Copy docker-compose file to main DP MTS directory
                scp -o StrictHostKeyChecking=no -r docker/docker-compose.yml root@${SERVER_IP}:/root/mythaistar/
                
                # Stop containers
                ssh -o StrictHostKeyChecking=no root@${SERVER_IP} docker stop mythaistar_client_compose_1
                ssh -o StrictHostKeyChecking=no root@${SERVER_IP} docker stop mythaistar_server_compose_1
                ssh -o StrictHostKeyChecking=no root@${SERVER_IP} cd mythaistar && docker-compose rm -f
                ssh -o StrictHostKeyChecking=no root@${SERVER_IP} cd mythaistar && docker-compose pull
                ssh -o StrictHostKeyChecking=no root@${SERVER_IP} cd mythaistar && docker-compose up --build -d
            """
        }
        sh 'echo \\"Application available at http://${SERVER_IP}:8091\\"'
    }
}