node {
    stage('Checking out MyThaiStar') {
        deleteDir()
        git branch: 'develop', credentialsId: 'github-devonfw-ci', url: 'https://github.com/oasp/my-thai-star/'
    }

    stage('Loading Custom Tools') {
        def node = tool name: 'Node 8.9 LTS', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
        env.PATH = "${node}/bin:${env.PATH}"
        tool 'Chrome-stable'
    }
    
    stage('Fresh Dependency Installation') {
        sh """
            cd angular
            npm install
        """
    }
    
    stage('Code Linting') {
        sh """
            cd angular
            npm run lint
        """
    }
    
    stage('Execute Angular tests') {
        sh """
            cd angular
            ng test --browsers ChromeHeadless --single-run
        """
    }
    
    stage('Build Application') {
        sh """
            cd angular
            ng build --prod --build-optimizer
        """
    }
    
    stage('Deployment') {
        sshagent (credentials: ['3d0fa2a4-5cf0-4cf5-a3fd-23655eb33c11']) {
            sh """
                cd angular
                # Copy resulting "dist" folder from workspace to deployment server
                scp -o StrictHostKeyChecking=no -r dist root@${SERVER_IP}:/root/mythaistar/angular/
                
                # Launch application in Docker container
                ssh -o StrictHostKeyChecking=no root@${SERVER_IP} docker rm -f mts-angular
                ssh -o StrictHostKeyChecking=no root@${SERVER_IP} docker run -itd --name=mts-angular -p 8090:80 cbelda/nginx-try-files
                ssh -o StrictHostKeyChecking=no root@${SERVER_IP} docker exec mts-angular bash -c \\"rm /usr/share/nginx/html/*\\"
                ssh -o StrictHostKeyChecking=no root@${SERVER_IP} docker cp mythaistar/angular/dist/. mts-angular:/usr/share/nginx/html/
            """
        }
        sh 'echo \\"Application available at http://${SERVER_IP}:8090\\"'
    }
}