node {
    stage 'Checking out my-thai-star from GitHub'
        node {
            git branch: 'develop', credentialsId: 'github-devonfw-ci', url: 'https://github.com/devonfw/my-thai-star/'
        }

    stage 'Loading Custom Tools'
        node {
            tool 'Node 6'
            tool 'Yarn'
            tool 'Angular CLI'
        }
    
    stage 'Fresh Dependency Installation'
        node {
            sh """
                cd angular
                find . -name "node_modules" -exec rm -rf '{}' +
                npm i
            """
        }
        
    stage 'Code Linting'
        try {
            node {
                sh """
                    cd angular
                    ng lint --format checkstyle
                """
            }
        } catch(err) {
            echo "Linting not passed:"
            currentBuild.result = 'FAILURE'
        }
    
    stage 'Execute Angular tests'
        node {
            sh """
                cd angular
                ng test --browsers PhantomJS --single-run
            """
        }
        
    stage 'Build Application'
        node {
            sh """
                cd angular
                ng build --aot --prod
            """
        }
    
    stage 'Deployment'
        input 'Should this build be deployed?'
            node {
                sshagent (credentials: ['3d0fa2a4-5cf0-4cf5-a3fd-23655eb33c11']) {
                    sh """
                        cd angular
                        # Copy resulting "dist" folder from workspace to deployment server
                        scp -o StrictHostKeyChecking=no -r dist root@10.40.235.244:/root/mythaistar/
                        
                        # Launch application in Docker container
                        ssh -o StrictHostKeyChecking=no root@10.40.235.244 docker rm -f mythaistar
                        ssh -o StrictHostKeyChecking=no root@10.40.235.244 docker run -itd --name=mythaistar -p 8090:80 nginx
                        ssh -o StrictHostKeyChecking=no root@10.40.235.244 docker exec mythaistar bash -c \\"rm /usr/share/nginx/html/*\\"
                        ssh -o StrictHostKeyChecking=no root@10.40.235.244 docker cp mythaistar/dist/. mythaistar:/usr/share/nginx/html/
                    
                    """
                }
                sh 'echo \\"Application available at http://de-mucdevondepl01:8090\\"'
            }
}