 apiVersion: v1
 kind: Service
 metadata:
   labels:
     app: devonfw-demo-java
   name: java
 spec:
   ports:
     - port: 8080
       targetPort: 8080
       protocol: TCP
   selector:
     app: devonfw-demo-java
