# 1. Build
FROM maven:3.6-jdk-11 AS build
WORKDIR /app
COPY java/mtsj/. /app
RUN mvn clean install

# 2. Deploy Java war
FROM adoptopenjdk/openjdk11:jre-11.0.4_11-alpine
WORKDIR /app
COPY --from=build /app/server/target/mythaistar-bootified.war /app/
ENTRYPOINT ["java","-jar","/app/mythaistar-bootified.war"]
EXPOSE 8081
