/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jan 12 15:20:23 CET 2018
 */
package com.capgemini.salesforcepoc.dto;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;

import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractDescribedSObjectBase;
import org.apache.camel.component.salesforce.api.dto.ChildRelationShip;
import org.apache.camel.component.salesforce.api.dto.InfoUrls;
import org.apache.camel.component.salesforce.api.dto.NamedLayoutInfo;
import org.apache.camel.component.salesforce.api.dto.RecordTypeInfo;
import org.apache.camel.component.salesforce.api.dto.SObjectDescription;
import org.apache.camel.component.salesforce.api.dto.SObjectDescriptionUrls;
import org.apache.camel.component.salesforce.api.dto.SObjectField;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject Lead
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
@XStreamAlias("Lead")
public class Lead extends AbstractDescribedSObjectBase {

    private static final SObjectDescription DESCRIPTION = createSObjectDescription();

    // MasterRecordId
    private String MasterRecordId;

    @JsonProperty("MasterRecordId")
    public String getMasterRecordId() {
        return this.MasterRecordId;
    }

    @JsonProperty("MasterRecordId")
    public void setMasterRecordId(String MasterRecordId) {
        this.MasterRecordId = MasterRecordId;
    }

    // LastName
    private String LastName;

    @JsonProperty("LastName")
    public String getLastName() {
        return this.LastName;
    }

    @JsonProperty("LastName")
    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    // FirstName
    private String FirstName;

    @JsonProperty("FirstName")
    public String getFirstName() {
        return this.FirstName;
    }

    @JsonProperty("FirstName")
    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    // Salutation
    @XStreamConverter(PicklistEnumConverter.class)
    private Lead_SalutationEnum Salutation;

    @JsonProperty("Salutation")
    public Lead_SalutationEnum getSalutation() {
        return this.Salutation;
    }

    @JsonProperty("Salutation")
    public void setSalutation(Lead_SalutationEnum Salutation) {
        this.Salutation = Salutation;
    }

    // RecordTypeId
    private String RecordTypeId;

    @JsonProperty("RecordTypeId")
    public String getRecordTypeId() {
        return this.RecordTypeId;
    }

    @JsonProperty("RecordTypeId")
    public void setRecordTypeId(String RecordTypeId) {
        this.RecordTypeId = RecordTypeId;
    }

    // Title
    private String Title;

    @JsonProperty("Title")
    public String getTitle() {
        return this.Title;
    }

    @JsonProperty("Title")
    public void setTitle(String Title) {
        this.Title = Title;
    }

    // Company
    private String Company;

    @JsonProperty("Company")
    public String getCompany() {
        return this.Company;
    }

    @JsonProperty("Company")
    public void setCompany(String Company) {
        this.Company = Company;
    }

    // Street
    private String Street;

    @JsonProperty("Street")
    public String getStreet() {
        return this.Street;
    }

    @JsonProperty("Street")
    public void setStreet(String Street) {
        this.Street = Street;
    }

    // City
    private String City;

    @JsonProperty("City")
    public String getCity() {
        return this.City;
    }

    @JsonProperty("City")
    public void setCity(String City) {
        this.City = City;
    }

    // State
    private String State;

    @JsonProperty("State")
    public String getState() {
        return this.State;
    }

    @JsonProperty("State")
    public void setState(String State) {
        this.State = State;
    }

    // PostalCode
    private String PostalCode;

    @JsonProperty("PostalCode")
    public String getPostalCode() {
        return this.PostalCode;
    }

    @JsonProperty("PostalCode")
    public void setPostalCode(String PostalCode) {
        this.PostalCode = PostalCode;
    }

    // Country
    private String Country;

    @JsonProperty("Country")
    public String getCountry() {
        return this.Country;
    }

    @JsonProperty("Country")
    public void setCountry(String Country) {
        this.Country = Country;
    }

    // Latitude
    private Double Latitude;

    @JsonProperty("Latitude")
    public Double getLatitude() {
        return this.Latitude;
    }

    @JsonProperty("Latitude")
    public void setLatitude(Double Latitude) {
        this.Latitude = Latitude;
    }

    // Longitude
    private Double Longitude;

    @JsonProperty("Longitude")
    public Double getLongitude() {
        return this.Longitude;
    }

    @JsonProperty("Longitude")
    public void setLongitude(Double Longitude) {
        this.Longitude = Longitude;
    }

    // Address
    private org.apache.camel.component.salesforce.api.dto.Address Address;

    @JsonProperty("Address")
    public org.apache.camel.component.salesforce.api.dto.Address getAddress() {
        return this.Address;
    }

    @JsonProperty("Address")
    public void setAddress(org.apache.camel.component.salesforce.api.dto.Address Address) {
        this.Address = Address;
    }

    // Phone
    private String Phone;

    @JsonProperty("Phone")
    public String getPhone() {
        return this.Phone;
    }

    @JsonProperty("Phone")
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    // MobilePhone
    private String MobilePhone;

    @JsonProperty("MobilePhone")
    public String getMobilePhone() {
        return this.MobilePhone;
    }

    @JsonProperty("MobilePhone")
    public void setMobilePhone(String MobilePhone) {
        this.MobilePhone = MobilePhone;
    }

    // Email
    private String Email;

    @JsonProperty("Email")
    public String getEmail() {
        return this.Email;
    }

    @JsonProperty("Email")
    public void setEmail(String Email) {
        this.Email = Email;
    }

    // Website
    private String Website;

    @JsonProperty("Website")
    public String getWebsite() {
        return this.Website;
    }

    @JsonProperty("Website")
    public void setWebsite(String Website) {
        this.Website = Website;
    }

    // PhotoUrl
    private String PhotoUrl;

    @JsonProperty("PhotoUrl")
    public String getPhotoUrl() {
        return this.PhotoUrl;
    }

    @JsonProperty("PhotoUrl")
    public void setPhotoUrl(String PhotoUrl) {
        this.PhotoUrl = PhotoUrl;
    }

    // Description
    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }

    // LeadSource
    @XStreamConverter(PicklistEnumConverter.class)
    private Lead_LeadSourceEnum LeadSource;

    @JsonProperty("LeadSource")
    public Lead_LeadSourceEnum getLeadSource() {
        return this.LeadSource;
    }

    @JsonProperty("LeadSource")
    public void setLeadSource(Lead_LeadSourceEnum LeadSource) {
        this.LeadSource = LeadSource;
    }

    // Status
    @XStreamConverter(PicklistEnumConverter.class)
    private Lead_StatusEnum Status;

    @JsonProperty("Status")
    public Lead_StatusEnum getStatus() {
        return this.Status;
    }

    @JsonProperty("Status")
    public void setStatus(Lead_StatusEnum Status) {
        this.Status = Status;
    }

    // Industry
    @XStreamConverter(PicklistEnumConverter.class)
    private Lead_IndustryEnum Industry;

    @JsonProperty("Industry")
    public Lead_IndustryEnum getIndustry() {
        return this.Industry;
    }

    @JsonProperty("Industry")
    public void setIndustry(Lead_IndustryEnum Industry) {
        this.Industry = Industry;
    }

    // Rating
    @XStreamConverter(PicklistEnumConverter.class)
    private Lead_RatingEnum Rating;

    @JsonProperty("Rating")
    public Lead_RatingEnum getRating() {
        return this.Rating;
    }

    @JsonProperty("Rating")
    public void setRating(Lead_RatingEnum Rating) {
        this.Rating = Rating;
    }

    // AnnualRevenue
    private Double AnnualRevenue;

    @JsonProperty("AnnualRevenue")
    public Double getAnnualRevenue() {
        return this.AnnualRevenue;
    }

    @JsonProperty("AnnualRevenue")
    public void setAnnualRevenue(Double AnnualRevenue) {
        this.AnnualRevenue = AnnualRevenue;
    }

    // NumberOfEmployees
    private Integer NumberOfEmployees;

    @JsonProperty("NumberOfEmployees")
    public Integer getNumberOfEmployees() {
        return this.NumberOfEmployees;
    }

    @JsonProperty("NumberOfEmployees")
    public void setNumberOfEmployees(Integer NumberOfEmployees) {
        this.NumberOfEmployees = NumberOfEmployees;
    }

    // IsConverted
    private Boolean IsConverted;

    @JsonProperty("IsConverted")
    public Boolean getIsConverted() {
        return this.IsConverted;
    }

    @JsonProperty("IsConverted")
    public void setIsConverted(Boolean IsConverted) {
        this.IsConverted = IsConverted;
    }

    // ConvertedDate
    private java.time.ZonedDateTime ConvertedDate;

    @JsonProperty("ConvertedDate")
    public java.time.ZonedDateTime getConvertedDate() {
        return this.ConvertedDate;
    }

    @JsonProperty("ConvertedDate")
    public void setConvertedDate(java.time.ZonedDateTime ConvertedDate) {
        this.ConvertedDate = ConvertedDate;
    }

    // ConvertedAccountId
    private String ConvertedAccountId;

    @JsonProperty("ConvertedAccountId")
    public String getConvertedAccountId() {
        return this.ConvertedAccountId;
    }

    @JsonProperty("ConvertedAccountId")
    public void setConvertedAccountId(String ConvertedAccountId) {
        this.ConvertedAccountId = ConvertedAccountId;
    }

    // ConvertedContactId
    private String ConvertedContactId;

    @JsonProperty("ConvertedContactId")
    public String getConvertedContactId() {
        return this.ConvertedContactId;
    }

    @JsonProperty("ConvertedContactId")
    public void setConvertedContactId(String ConvertedContactId) {
        this.ConvertedContactId = ConvertedContactId;
    }

    // ConvertedOpportunityId
    private String ConvertedOpportunityId;

    @JsonProperty("ConvertedOpportunityId")
    public String getConvertedOpportunityId() {
        return this.ConvertedOpportunityId;
    }

    @JsonProperty("ConvertedOpportunityId")
    public void setConvertedOpportunityId(String ConvertedOpportunityId) {
        this.ConvertedOpportunityId = ConvertedOpportunityId;
    }

    // IsUnreadByOwner
    private Boolean IsUnreadByOwner;

    @JsonProperty("IsUnreadByOwner")
    public Boolean getIsUnreadByOwner() {
        return this.IsUnreadByOwner;
    }

    @JsonProperty("IsUnreadByOwner")
    public void setIsUnreadByOwner(Boolean IsUnreadByOwner) {
        this.IsUnreadByOwner = IsUnreadByOwner;
    }

    // Jigsaw
    private String Jigsaw;

    @JsonProperty("Jigsaw")
    public String getJigsaw() {
        return this.Jigsaw;
    }

    @JsonProperty("Jigsaw")
    public void setJigsaw(String Jigsaw) {
        this.Jigsaw = Jigsaw;
    }

    // JigsawContactId
    private String JigsawContactId;

    @JsonProperty("JigsawContactId")
    public String getJigsawContactId() {
        return this.JigsawContactId;
    }

    @JsonProperty("JigsawContactId")
    public void setJigsawContactId(String JigsawContactId) {
        this.JigsawContactId = JigsawContactId;
    }

    // EmailBouncedReason
    private String EmailBouncedReason;

    @JsonProperty("EmailBouncedReason")
    public String getEmailBouncedReason() {
        return this.EmailBouncedReason;
    }

    @JsonProperty("EmailBouncedReason")
    public void setEmailBouncedReason(String EmailBouncedReason) {
        this.EmailBouncedReason = EmailBouncedReason;
    }

    // EmailBouncedDate
    private java.time.ZonedDateTime EmailBouncedDate;

    @JsonProperty("EmailBouncedDate")
    public java.time.ZonedDateTime getEmailBouncedDate() {
        return this.EmailBouncedDate;
    }

    @JsonProperty("EmailBouncedDate")
    public void setEmailBouncedDate(java.time.ZonedDateTime EmailBouncedDate) {
        this.EmailBouncedDate = EmailBouncedDate;
    }

    // AC_Event__c
    private String AC_Event__c;

    @JsonProperty("AC_Event__c")
    public String getAC_Event__c() {
        return this.AC_Event__c;
    }

    @JsonProperty("AC_Event__c")
    public void setAC_Event__c(String AC_Event__c) {
        this.AC_Event__c = AC_Event__c;
    }

    // Skills__c
    @XStreamConverter(PicklistEnumConverter.class)
    private Lead_SkillsEnum Skills__c;

    @JsonProperty("Skills__c")
    public Lead_SkillsEnum getSkills__c() {
        return this.Skills__c;
    }

    @JsonProperty("Skills__c")
    public void setSkills__c(Lead_SkillsEnum Skills__c) {
        this.Skills__c = Skills__c;
    }

    // Other_Skills__c
    private String Other_Skills__c;

    @JsonProperty("Other_Skills__c")
    public String getOther_Skills__c() {
        return this.Other_Skills__c;
    }

    @JsonProperty("Other_Skills__c")
    public void setOther_Skills__c(String Other_Skills__c) {
        this.Other_Skills__c = Other_Skills__c;
    }

    // Event_start_Date__c
    private java.time.ZonedDateTime Event_start_Date__c;

    @JsonProperty("Event_start_Date__c")
    public java.time.ZonedDateTime getEvent_start_Date__c() {
        return this.Event_start_Date__c;
    }

    @JsonProperty("Event_start_Date__c")
    public void setEvent_start_Date__c(java.time.ZonedDateTime Event_start_Date__c) {
        this.Event_start_Date__c = Event_start_Date__c;
    }

    // Event_End_Date__c
    private java.time.ZonedDateTime Event_End_Date__c;

    @JsonProperty("Event_End_Date__c")
    public java.time.ZonedDateTime getEvent_End_Date__c() {
        return this.Event_End_Date__c;
    }

    @JsonProperty("Event_End_Date__c")
    public void setEvent_End_Date__c(java.time.ZonedDateTime Event_End_Date__c) {
        this.Event_End_Date__c = Event_End_Date__c;
    }

    // Event_Name__c
    private String Event_Name__c;

    @JsonProperty("Event_Name__c")
    public String getEvent_Name__c() {
        return this.Event_Name__c;
    }

    @JsonProperty("Event_Name__c")
    public void setEvent_Name__c(String Event_Name__c) {
        this.Event_Name__c = Event_Name__c;
    }

    // Event_Venue__c
    private String Event_Venue__c;

    @JsonProperty("Event_Venue__c")
    public String getEvent_Venue__c() {
        return this.Event_Venue__c;
    }

    @JsonProperty("Event_Venue__c")
    public void setEvent_Venue__c(String Event_Venue__c) {
        this.Event_Venue__c = Event_Venue__c;
    }

    // Sent_Mail__c
    private Boolean Sent_Mail__c;

    @JsonProperty("Sent_Mail__c")
    public Boolean getSent_Mail__c() {
        return this.Sent_Mail__c;
    }

    @JsonProperty("Sent_Mail__c")
    public void setSent_Mail__c(Boolean Sent_Mail__c) {
        this.Sent_Mail__c = Sent_Mail__c;
    }

    // sf4twitter__Fcbk_Image_Url__c
    private String sf4twitter__Fcbk_Image_Url__c;

    @JsonProperty("sf4twitter__Fcbk_Image_Url__c")
    public String getsf4twitter__Fcbk_Image_Url__c() {
        return this.sf4twitter__Fcbk_Image_Url__c;
    }

    @JsonProperty("sf4twitter__Fcbk_Image_Url__c")
    public void setsf4twitter__Fcbk_Image_Url__c(String sf4twitter__Fcbk_Image_Url__c) {
        this.sf4twitter__Fcbk_Image_Url__c = sf4twitter__Fcbk_Image_Url__c;
    }

    // sf4twitter__Fcbk_Picture__c
    private String sf4twitter__Fcbk_Picture__c;

    @JsonProperty("sf4twitter__Fcbk_Picture__c")
    public String getsf4twitter__Fcbk_Picture__c() {
        return this.sf4twitter__Fcbk_Picture__c;
    }

    @JsonProperty("sf4twitter__Fcbk_Picture__c")
    public void setsf4twitter__Fcbk_Picture__c(String sf4twitter__Fcbk_Picture__c) {
        this.sf4twitter__Fcbk_Picture__c = sf4twitter__Fcbk_Picture__c;
    }

    // sf4twitter__Fcbk_Profile_Url__c
    private String sf4twitter__Fcbk_Profile_Url__c;

    @JsonProperty("sf4twitter__Fcbk_Profile_Url__c")
    public String getsf4twitter__Fcbk_Profile_Url__c() {
        return this.sf4twitter__Fcbk_Profile_Url__c;
    }

    @JsonProperty("sf4twitter__Fcbk_Profile_Url__c")
    public void setsf4twitter__Fcbk_Profile_Url__c(String sf4twitter__Fcbk_Profile_Url__c) {
        this.sf4twitter__Fcbk_Profile_Url__c = sf4twitter__Fcbk_Profile_Url__c;
    }

    // sf4twitter__Fcbk_User_Id__c
    private String sf4twitter__Fcbk_User_Id__c;

    @JsonProperty("sf4twitter__Fcbk_User_Id__c")
    public String getsf4twitter__Fcbk_User_Id__c() {
        return this.sf4twitter__Fcbk_User_Id__c;
    }

    @JsonProperty("sf4twitter__Fcbk_User_Id__c")
    public void setsf4twitter__Fcbk_User_Id__c(String sf4twitter__Fcbk_User_Id__c) {
        this.sf4twitter__Fcbk_User_Id__c = sf4twitter__Fcbk_User_Id__c;
    }

    // sf4twitter__Fcbk_Username__c
    private String sf4twitter__Fcbk_Username__c;

    @JsonProperty("sf4twitter__Fcbk_Username__c")
    public String getsf4twitter__Fcbk_Username__c() {
        return this.sf4twitter__Fcbk_Username__c;
    }

    @JsonProperty("sf4twitter__Fcbk_Username__c")
    public void setsf4twitter__Fcbk_Username__c(String sf4twitter__Fcbk_Username__c) {
        this.sf4twitter__Fcbk_Username__c = sf4twitter__Fcbk_Username__c;
    }

    // sf4twitter__Follow_Status__c
    private String sf4twitter__Follow_Status__c;

    @JsonProperty("sf4twitter__Follow_Status__c")
    public String getsf4twitter__Follow_Status__c() {
        return this.sf4twitter__Follow_Status__c;
    }

    @JsonProperty("sf4twitter__Follow_Status__c")
    public void setsf4twitter__Follow_Status__c(String sf4twitter__Follow_Status__c) {
        this.sf4twitter__Follow_Status__c = sf4twitter__Follow_Status__c;
    }

    // sf4twitter__Klout_Number__c
    private Double sf4twitter__Klout_Number__c;

    @JsonProperty("sf4twitter__Klout_Number__c")
    public Double getsf4twitter__Klout_Number__c() {
        return this.sf4twitter__Klout_Number__c;
    }

    @JsonProperty("sf4twitter__Klout_Number__c")
    public void setsf4twitter__Klout_Number__c(Double sf4twitter__Klout_Number__c) {
        this.sf4twitter__Klout_Number__c = sf4twitter__Klout_Number__c;
    }

    // sf4twitter__Klout_Score__c
    private String sf4twitter__Klout_Score__c;

    @JsonProperty("sf4twitter__Klout_Score__c")
    public String getsf4twitter__Klout_Score__c() {
        return this.sf4twitter__Klout_Score__c;
    }

    @JsonProperty("sf4twitter__Klout_Score__c")
    public void setsf4twitter__Klout_Score__c(String sf4twitter__Klout_Score__c) {
        this.sf4twitter__Klout_Score__c = sf4twitter__Klout_Score__c;
    }

    // sf4twitter__Origin__c
    @XStreamConverter(PicklistEnumConverter.class)
    private Lead_sf4twitter__OriginEnum sf4twitter__Origin__c;

    @JsonProperty("sf4twitter__Origin__c")
    public Lead_sf4twitter__OriginEnum getsf4twitter__Origin__c() {
        return this.sf4twitter__Origin__c;
    }

    @JsonProperty("sf4twitter__Origin__c")
    public void setsf4twitter__Origin__c(Lead_sf4twitter__OriginEnum sf4twitter__Origin__c) {
        this.sf4twitter__Origin__c = sf4twitter__Origin__c;
    }

    // sf4twitter__Twitter_Bio__c
    private String sf4twitter__Twitter_Bio__c;

    @JsonProperty("sf4twitter__Twitter_Bio__c")
    public String getsf4twitter__Twitter_Bio__c() {
        return this.sf4twitter__Twitter_Bio__c;
    }

    @JsonProperty("sf4twitter__Twitter_Bio__c")
    public void setsf4twitter__Twitter_Bio__c(String sf4twitter__Twitter_Bio__c) {
        this.sf4twitter__Twitter_Bio__c = sf4twitter__Twitter_Bio__c;
    }

    // sf4twitter__Twitter_Creation_Date__c
    private java.time.ZonedDateTime sf4twitter__Twitter_Creation_Date__c;

    @JsonProperty("sf4twitter__Twitter_Creation_Date__c")
    public java.time.ZonedDateTime getsf4twitter__Twitter_Creation_Date__c() {
        return this.sf4twitter__Twitter_Creation_Date__c;
    }

    @JsonProperty("sf4twitter__Twitter_Creation_Date__c")
    public void setsf4twitter__Twitter_Creation_Date__c(java.time.ZonedDateTime sf4twitter__Twitter_Creation_Date__c) {
        this.sf4twitter__Twitter_Creation_Date__c = sf4twitter__Twitter_Creation_Date__c;
    }

    // sf4twitter__Twitter_Follower_count__c
    private Double sf4twitter__Twitter_Follower_count__c;

    @JsonProperty("sf4twitter__Twitter_Follower_count__c")
    public Double getsf4twitter__Twitter_Follower_count__c() {
        return this.sf4twitter__Twitter_Follower_count__c;
    }

    @JsonProperty("sf4twitter__Twitter_Follower_count__c")
    public void setsf4twitter__Twitter_Follower_count__c(Double sf4twitter__Twitter_Follower_count__c) {
        this.sf4twitter__Twitter_Follower_count__c = sf4twitter__Twitter_Follower_count__c;
    }

    // sf4twitter__Twitter_Following_count__c
    private Double sf4twitter__Twitter_Following_count__c;

    @JsonProperty("sf4twitter__Twitter_Following_count__c")
    public Double getsf4twitter__Twitter_Following_count__c() {
        return this.sf4twitter__Twitter_Following_count__c;
    }

    @JsonProperty("sf4twitter__Twitter_Following_count__c")
    public void setsf4twitter__Twitter_Following_count__c(Double sf4twitter__Twitter_Following_count__c) {
        this.sf4twitter__Twitter_Following_count__c = sf4twitter__Twitter_Following_count__c;
    }

    // sf4twitter__Twitter_Image_Url__c
    private String sf4twitter__Twitter_Image_Url__c;

    @JsonProperty("sf4twitter__Twitter_Image_Url__c")
    public String getsf4twitter__Twitter_Image_Url__c() {
        return this.sf4twitter__Twitter_Image_Url__c;
    }

    @JsonProperty("sf4twitter__Twitter_Image_Url__c")
    public void setsf4twitter__Twitter_Image_Url__c(String sf4twitter__Twitter_Image_Url__c) {
        this.sf4twitter__Twitter_Image_Url__c = sf4twitter__Twitter_Image_Url__c;
    }

    // sf4twitter__Twitter_Last_tweet__c
    private java.time.ZonedDateTime sf4twitter__Twitter_Last_tweet__c;

    @JsonProperty("sf4twitter__Twitter_Last_tweet__c")
    public java.time.ZonedDateTime getsf4twitter__Twitter_Last_tweet__c() {
        return this.sf4twitter__Twitter_Last_tweet__c;
    }

    @JsonProperty("sf4twitter__Twitter_Last_tweet__c")
    public void setsf4twitter__Twitter_Last_tweet__c(java.time.ZonedDateTime sf4twitter__Twitter_Last_tweet__c) {
        this.sf4twitter__Twitter_Last_tweet__c = sf4twitter__Twitter_Last_tweet__c;
    }

    // sf4twitter__Twitter_Location__c
    private String sf4twitter__Twitter_Location__c;

    @JsonProperty("sf4twitter__Twitter_Location__c")
    public String getsf4twitter__Twitter_Location__c() {
        return this.sf4twitter__Twitter_Location__c;
    }

    @JsonProperty("sf4twitter__Twitter_Location__c")
    public void setsf4twitter__Twitter_Location__c(String sf4twitter__Twitter_Location__c) {
        this.sf4twitter__Twitter_Location__c = sf4twitter__Twitter_Location__c;
    }

    // sf4twitter__Twitter_Picture__c
    private String sf4twitter__Twitter_Picture__c;

    @JsonProperty("sf4twitter__Twitter_Picture__c")
    public String getsf4twitter__Twitter_Picture__c() {
        return this.sf4twitter__Twitter_Picture__c;
    }

    @JsonProperty("sf4twitter__Twitter_Picture__c")
    public void setsf4twitter__Twitter_Picture__c(String sf4twitter__Twitter_Picture__c) {
        this.sf4twitter__Twitter_Picture__c = sf4twitter__Twitter_Picture__c;
    }

    // sf4twitter__Twitter_Status_count__c
    private Double sf4twitter__Twitter_Status_count__c;

    @JsonProperty("sf4twitter__Twitter_Status_count__c")
    public Double getsf4twitter__Twitter_Status_count__c() {
        return this.sf4twitter__Twitter_Status_count__c;
    }

    @JsonProperty("sf4twitter__Twitter_Status_count__c")
    public void setsf4twitter__Twitter_Status_count__c(Double sf4twitter__Twitter_Status_count__c) {
        this.sf4twitter__Twitter_Status_count__c = sf4twitter__Twitter_Status_count__c;
    }

    // sf4twitter__Twitter_User_Id__c
    private String sf4twitter__Twitter_User_Id__c;

    @JsonProperty("sf4twitter__Twitter_User_Id__c")
    public String getsf4twitter__Twitter_User_Id__c() {
        return this.sf4twitter__Twitter_User_Id__c;
    }

    @JsonProperty("sf4twitter__Twitter_User_Id__c")
    public void setsf4twitter__Twitter_User_Id__c(String sf4twitter__Twitter_User_Id__c) {
        this.sf4twitter__Twitter_User_Id__c = sf4twitter__Twitter_User_Id__c;
    }

    // sf4twitter__Twitter_Username__c
    private String sf4twitter__Twitter_Username__c;

    @JsonProperty("sf4twitter__Twitter_Username__c")
    public String getsf4twitter__Twitter_Username__c() {
        return this.sf4twitter__Twitter_Username__c;
    }

    @JsonProperty("sf4twitter__Twitter_Username__c")
    public void setsf4twitter__Twitter_Username__c(String sf4twitter__Twitter_Username__c) {
        this.sf4twitter__Twitter_Username__c = sf4twitter__Twitter_Username__c;
    }

    // sf4twitter__followed__c
    private Boolean sf4twitter__followed__c;

    @JsonProperty("sf4twitter__followed__c")
    public Boolean getsf4twitter__followed__c() {
        return this.sf4twitter__followed__c;
    }

    @JsonProperty("sf4twitter__followed__c")
    public void setsf4twitter__followed__c(Boolean sf4twitter__followed__c) {
        this.sf4twitter__followed__c = sf4twitter__followed__c;
    }

    // Event_Owner__c
    private String Event_Owner__c;

    @JsonProperty("Event_Owner__c")
    public String getEvent_Owner__c() {
        return this.Event_Owner__c;
    }

    @JsonProperty("Event_Owner__c")
    public void setEvent_Owner__c(String Event_Owner__c) {
        this.Event_Owner__c = Event_Owner__c;
    }

    // EventOwnerEmailId__c
    private String EventOwnerEmailId__c;

    @JsonProperty("EventOwnerEmailId__c")
    public String getEventOwnerEmailId__c() {
        return this.EventOwnerEmailId__c;
    }

    @JsonProperty("EventOwnerEmailId__c")
    public void setEventOwnerEmailId__c(String EventOwnerEmailId__c) {
        this.EventOwnerEmailId__c = EventOwnerEmailId__c;
    }


    @Override
    public final SObjectDescription description() {
        return DESCRIPTION;
    }

    private static SObjectDescription createSObjectDescription() {
        final SObjectDescription description = new SObjectDescription();



        final List<SObjectField> fields1 = new ArrayList<>();
        description.setFields(fields1);

        final SObjectField sObjectField1 = createField("Id", "Lead ID", "id", "tns:ID", 18, false, false, false, false, false, false, true);
        fields1.add(sObjectField1);
        final SObjectField sObjectField2 = createField("IsDeleted", "Deleted", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField2);
        final SObjectField sObjectField3 = createField("MasterRecordId", "Master Record ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField3);
        final SObjectField sObjectField4 = createField("LastName", "Last Name", "string", "xsd:string", 80, false, false, false, false, false, false, false);
        fields1.add(sObjectField4);
        final SObjectField sObjectField5 = createField("FirstName", "First Name", "string", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField5);
        final SObjectField sObjectField6 = createField("Salutation", "Salutation", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField6);
        final SObjectField sObjectField7 = createField("Name", "Full Name", "string", "xsd:string", 121, false, false, true, false, false, false, false);
        fields1.add(sObjectField7);
        final SObjectField sObjectField8 = createField("RecordTypeId", "Record Type ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField8);
        final SObjectField sObjectField9 = createField("Title", "Title", "string", "xsd:string", 128, false, true, false, false, false, false, false);
        fields1.add(sObjectField9);
        final SObjectField sObjectField10 = createField("Company", "Company", "string", "xsd:string", 255, false, false, false, false, false, false, false);
        fields1.add(sObjectField10);
        final SObjectField sObjectField11 = createField("Street", "Street", "textarea", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField11);
        final SObjectField sObjectField12 = createField("City", "City", "string", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField12);
        final SObjectField sObjectField13 = createField("State", "State/Province", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField13);
        final SObjectField sObjectField14 = createField("PostalCode", "Zip/Postal Code", "string", "xsd:string", 20, false, true, false, false, false, false, false);
        fields1.add(sObjectField14);
        final SObjectField sObjectField15 = createField("Country", "Country", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField15);
        final SObjectField sObjectField16 = createField("Latitude", "Latitude", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField16);
        final SObjectField sObjectField17 = createField("Longitude", "Longitude", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField17);
        final SObjectField sObjectField18 = createField("Address", "Address", "address", "urn:address", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField18);
        final SObjectField sObjectField19 = createField("Phone", "Phone", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField19);
        final SObjectField sObjectField20 = createField("MobilePhone", "Mobile Phone", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField20);
        final SObjectField sObjectField21 = createField("Email", "Email", "email", "xsd:string", 80, false, true, false, false, false, false, true);
        fields1.add(sObjectField21);
        final SObjectField sObjectField22 = createField("Website", "Website", "url", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField22);
        final SObjectField sObjectField23 = createField("PhotoUrl", "Photo URL", "url", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField23);
        final SObjectField sObjectField24 = createField("Description", "Description", "textarea", "xsd:string", 32000, false, true, false, false, false, false, false);
        fields1.add(sObjectField24);
        final SObjectField sObjectField25 = createField("LeadSource", "Lead Source", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField25);
        final SObjectField sObjectField26 = createField("Status", "Status", "picklist", "xsd:string", 40, false, false, false, false, false, false, false);
        fields1.add(sObjectField26);
        final SObjectField sObjectField27 = createField("Industry", "Industry", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField27);
        final SObjectField sObjectField28 = createField("Rating", "Rating", "picklist", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField28);
        final SObjectField sObjectField29 = createField("AnnualRevenue", "Annual Revenue", "currency", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField29);
        final SObjectField sObjectField30 = createField("NumberOfEmployees", "Employees", "int", "xsd:int", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField30);
        final SObjectField sObjectField31 = createField("OwnerId", "Owner ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField31);
        final SObjectField sObjectField32 = createField("IsConverted", "Converted", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField32);
        final SObjectField sObjectField33 = createField("ConvertedDate", "Converted Date", "date", "xsd:date", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField33);
        final SObjectField sObjectField34 = createField("ConvertedAccountId", "Converted Account ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField34);
        final SObjectField sObjectField35 = createField("ConvertedContactId", "Converted Contact ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField35);
        final SObjectField sObjectField36 = createField("ConvertedOpportunityId", "Converted Opportunity ID", "reference", "tns:ID", 18, false, true, false, false, false, false, false);
        fields1.add(sObjectField36);
        final SObjectField sObjectField37 = createField("IsUnreadByOwner", "Unread By Owner", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField37);
        final SObjectField sObjectField38 = createField("CreatedDate", "Created Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField38);
        final SObjectField sObjectField39 = createField("CreatedById", "Created By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField39);
        final SObjectField sObjectField40 = createField("LastModifiedDate", "Last Modified Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField40);
        final SObjectField sObjectField41 = createField("LastModifiedById", "Last Modified By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField41);
        final SObjectField sObjectField42 = createField("SystemModstamp", "System Modstamp", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField42);
        final SObjectField sObjectField43 = createField("LastActivityDate", "Last Activity", "date", "xsd:date", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField43);
        final SObjectField sObjectField44 = createField("LastViewedDate", "Last Viewed Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField44);
        final SObjectField sObjectField45 = createField("LastReferencedDate", "Last Referenced Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField45);
        final SObjectField sObjectField46 = createField("Jigsaw", "Data.com Key", "string", "xsd:string", 20, false, true, false, false, false, false, false);
        fields1.add(sObjectField46);
        final SObjectField sObjectField47 = createField("JigsawContactId", "Jigsaw Contact ID", "string", "xsd:string", 20, false, true, false, false, false, false, false);
        fields1.add(sObjectField47);
        final SObjectField sObjectField48 = createField("EmailBouncedReason", "Email Bounced Reason", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField48);
        final SObjectField sObjectField49 = createField("EmailBouncedDate", "Email Bounced Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField49);
        final SObjectField sObjectField50 = createField("AC_Event__c", "AC Event", "reference", "tns:ID", 18, false, true, false, false, true, false, false);
        fields1.add(sObjectField50);
        final SObjectField sObjectField51 = createField("Skills__c", "Skills", "picklist", "xsd:string", 255, false, true, false, false, true, false, false);
        fields1.add(sObjectField51);
        final SObjectField sObjectField52 = createField("Other_Skills__c", "Other Skills", "textarea", "xsd:string", 32768, false, true, false, false, true, false, false);
        fields1.add(sObjectField52);
        final SObjectField sObjectField53 = createField("Event_start_Date__c", "Event start Date", "datetime", "xsd:dateTime", 0, false, true, false, false, true, false, false);
        fields1.add(sObjectField53);
        final SObjectField sObjectField54 = createField("Event_End_Date__c", "Event End Date", "datetime", "xsd:dateTime", 0, false, true, false, false, true, false, false);
        fields1.add(sObjectField54);
        final SObjectField sObjectField55 = createField("Event_Name__c", "Event Name", "string", "xsd:string", 1300, false, true, false, false, true, false, false);
        fields1.add(sObjectField55);
        final SObjectField sObjectField56 = createField("Event_Venue__c", "Event Venue", "string", "xsd:string", 1300, false, true, false, false, true, false, false);
        fields1.add(sObjectField56);
        final SObjectField sObjectField57 = createField("Sent_Mail__c", "Sent Mail", "boolean", "xsd:boolean", 0, false, false, false, false, true, false, false);
        fields1.add(sObjectField57);
        final SObjectField sObjectField58 = createField("sf4twitter__Fcbk_Image_Url__c", "Facebook Image Url", "url", "xsd:string", 255, false, true, false, false, true, false, false);
        fields1.add(sObjectField58);
        final SObjectField sObjectField59 = createField("sf4twitter__Fcbk_Picture__c", "Facebook Picture", "string", "xsd:string", 1300, false, true, false, false, true, false, false);
        fields1.add(sObjectField59);
        final SObjectField sObjectField60 = createField("sf4twitter__Fcbk_Profile_Url__c", "Facebook Profile Url", "url", "xsd:string", 255, false, true, false, false, true, false, false);
        fields1.add(sObjectField60);
        final SObjectField sObjectField61 = createField("sf4twitter__Fcbk_User_Id__c", "Facebook User Id", "string", "xsd:string", 255, true, true, false, true, true, true, true);
        fields1.add(sObjectField61);
        final SObjectField sObjectField62 = createField("sf4twitter__Fcbk_Username__c", "Facebook Username", "string", "xsd:string", 255, false, true, false, false, true, false, false);
        fields1.add(sObjectField62);
        final SObjectField sObjectField63 = createField("sf4twitter__Follow_Status__c", "Following on Twitter", "string", "xsd:string", 1300, false, true, false, false, true, false, false);
        fields1.add(sObjectField63);
        final SObjectField sObjectField64 = createField("sf4twitter__Klout_Number__c", "Klout Number", "double", "xsd:double", 0, false, true, false, false, true, false, false);
        fields1.add(sObjectField64);
        final SObjectField sObjectField65 = createField("sf4twitter__Klout_Score__c", "Klout Score", "string", "xsd:string", 1300, false, true, false, false, true, false, false);
        fields1.add(sObjectField65);
        final SObjectField sObjectField66 = createField("sf4twitter__Origin__c", "Origin", "picklist", "xsd:string", 255, false, true, false, false, true, false, false);
        fields1.add(sObjectField66);
        final SObjectField sObjectField67 = createField("sf4twitter__Twitter_Bio__c", "Twitter Bio", "string", "xsd:string", 255, false, true, false, false, true, false, false);
        fields1.add(sObjectField67);
        final SObjectField sObjectField68 = createField("sf4twitter__Twitter_Creation_Date__c", "Twitter Creation Date", "datetime", "xsd:dateTime", 0, false, true, false, false, true, false, false);
        fields1.add(sObjectField68);
        final SObjectField sObjectField69 = createField("sf4twitter__Twitter_Follower_count__c", "Twitter Follower count", "double", "xsd:double", 0, false, true, false, false, true, false, false);
        fields1.add(sObjectField69);
        final SObjectField sObjectField70 = createField("sf4twitter__Twitter_Following_count__c", "Twitter Following count", "double", "xsd:double", 0, false, true, false, false, true, false, false);
        fields1.add(sObjectField70);
        final SObjectField sObjectField71 = createField("sf4twitter__Twitter_Image_Url__c", "Twitter Image Url", "url", "xsd:string", 255, false, true, false, false, true, false, false);
        fields1.add(sObjectField71);
        final SObjectField sObjectField72 = createField("sf4twitter__Twitter_Last_tweet__c", "Twitter Last tweet", "datetime", "xsd:dateTime", 0, false, true, false, false, true, false, false);
        fields1.add(sObjectField72);
        final SObjectField sObjectField73 = createField("sf4twitter__Twitter_Location__c", "Twitter Location", "string", "xsd:string", 255, false, true, false, false, true, false, false);
        fields1.add(sObjectField73);
        final SObjectField sObjectField74 = createField("sf4twitter__Twitter_Picture__c", "Twitter Picture", "string", "xsd:string", 1300, false, true, false, false, true, false, false);
        fields1.add(sObjectField74);
        final SObjectField sObjectField75 = createField("sf4twitter__Twitter_Status_count__c", "Twitter Status count", "double", "xsd:double", 0, false, true, false, false, true, false, false);
        fields1.add(sObjectField75);
        final SObjectField sObjectField76 = createField("sf4twitter__Twitter_User_Id__c", "Twitter User Id", "string", "xsd:string", 255, true, true, false, true, true, true, true);
        fields1.add(sObjectField76);
        final SObjectField sObjectField77 = createField("sf4twitter__Twitter_Username__c", "Twitter Username", "string", "xsd:string", 50, false, true, false, false, true, false, false);
        fields1.add(sObjectField77);
        final SObjectField sObjectField78 = createField("sf4twitter__followed__c", "Followed", "boolean", "xsd:boolean", 0, false, false, false, false, true, false, false);
        fields1.add(sObjectField78);
        final SObjectField sObjectField79 = createField("Event_Owner__c", "Event Owner", "string", "xsd:string", 1300, false, true, false, false, true, false, false);
        fields1.add(sObjectField79);
        final SObjectField sObjectField80 = createField("EventOwnerEmailId__c", "EventOwnerEmailId", "string", "xsd:string", 1300, false, true, false, false, true, false, false);
        fields1.add(sObjectField80);

        description.setLabelPlural("Leads");
        description.setLabel("Lead");

        final SObjectDescriptionUrls sObjectDescriptionUrls1 = new SObjectDescriptionUrls();
        sObjectDescriptionUrls1.setDescribe("/services/data/v34.0/sobjects/Lead/describe");
        sObjectDescriptionUrls1.setLayouts("/services/data/v34.0/sobjects/Lead/describe/layouts");
        sObjectDescriptionUrls1.setSobject("/services/data/v34.0/sobjects/Lead");
        sObjectDescriptionUrls1.setQuickActions("/services/data/v34.0/sobjects/Lead/quickActions");
        sObjectDescriptionUrls1.setUiEditTemplate("https://merck-capgemini.my.salesforce.com/{ID}/e");
        sObjectDescriptionUrls1.setRowTemplate("/services/data/v34.0/sobjects/Lead/{ID}");
        sObjectDescriptionUrls1.setListviews("/services/data/v34.0/sobjects/Lead/listviews");
        sObjectDescriptionUrls1.setCompactLayouts("/services/data/v34.0/sobjects/Lead/describe/compactLayouts");
        sObjectDescriptionUrls1.setApprovalLayouts("/services/data/v34.0/sobjects/Lead/describe/approvalLayouts");
        sObjectDescriptionUrls1.setUiNewRecord("https://merck-capgemini.my.salesforce.com/00Q/e");
        sObjectDescriptionUrls1.setUiDetailTemplate("https://merck-capgemini.my.salesforce.com/{ID}");
        description.setUrls(sObjectDescriptionUrls1);
        description.setName("Lead");

        return description;
    }
}
