/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jan 12 15:20:23 CET 2018
 */
package com.capgemini.salesforcepoc.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Skills__c
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Lead_SkillsEnum {

    // Android
    ANDROID("Android"),
    // C
    C("C"),
    // C++
    C__("C++"),
    // Java
    JAVA("Java"),
    // Salesforce
    SALESFORCE("Salesforce");

    final String value;

    private Lead_SkillsEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Lead_SkillsEnum fromValue(String value) {
        for (Lead_SkillsEnum e : Lead_SkillsEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
