/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jan 12 15:20:23 CET 2018
 */
package com.capgemini.salesforcepoc.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Lead_StatusEnum {

    // Contacted
    CONTACTED("Contacted"),
    // New
    NEW("New"),
    // Nurturing
    NURTURING("Nurturing"),
    // Qualified
    QUALIFIED("Qualified"),
    // Unqualified
    UNQUALIFIED("Unqualified");

    final String value;

    private Lead_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Lead_StatusEnum fromValue(String value) {
        for (Lead_StatusEnum e : Lead_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
