/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jan 12 15:20:23 CET 2018
 */
package com.capgemini.salesforcepoc.dto;

import com.thoughtworks.xstream.annotations.XStreamImplicit;
import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;
import javax.annotation.Generated;

/**
 * Salesforce QueryRecords DTO for type Lead
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public class QueryRecordsLead extends AbstractQueryRecordsBase {

    @XStreamImplicit
    private List<Lead> records;

    public List<Lead> getRecords() {
        return records;
    }

    public void setRecords(List<Lead> records) {
        this.records = records;
    }
}
