export enum Configuration {
  HOST = 'HOST',
  PORT = 'PORT',
  DB_URI = 'DB_URI',
  JWT_KEY = 'JWT_KEY',
  SWAGGER_TITLE = 'SWAGGER_TITLE',
  SWAGGER_DESCRIPTION = 'SWAGGER_DESCRIPTION',
  SWAGGER_VERSION = 'SWAGGER_VERSION',
  SWAGGER_BASEPATH = 'SWAGGER_BASEPATH',
}
