 apiVersion: v1
 kind: Service
 metadata:
   labels:
     app: devonfw-demo-angular
   name: angular
 spec:
   ports:
   - port: 80
     targetPort: 80
     protocol: TCP
   selector:
     app: devonfw-demo-angular
