FROM nginx:alpine-perl

COPY nginx.conf /etc/nginx/nginx.conf
COPY . /var/www/
RUN rm -f ./var/www/nginx.conf

RUN chown -R nginx /var/cache/nginx && chmod -R 755 /var/cache/nginx && chmod 777 /var/cache/nginx
RUN chown -R nginx /run && chmod -R 755 /run && chmod 777 /run

EXPOSE 8080

HEALTHCHECK --interval=60s --timeout=30s --start-period=1s --retries=3 CMD curl --fail http://localhost/health || exit 1
CMD ["nginx", "-g", "daemon off;"]
