# Only used for TravisCI purposes

FROM node:lts AS build
WORKDIR /app
COPY . /app

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
        && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
        && apt-get update && apt-get -y install google-chrome-stable

RUN yarn
RUN yarn test:ci && yarn lint && yarn build --configuration=docker
