 apiVersion: v1
 kind: Service
 metadata:
   labels:
     app: devonfw-demo-edge
   name: edge
 spec:
   ports:
   - port: 80
     targetPort: 80
     protocol: TCP
   selector:
     app: devonfw-demo-edge
